set(SAIKO_INJECTOR_VERSION_MAJOR 1)
set(SAIKO_INJECTOR_VERSION_MINOR 0)
set(SAIKO_INJECTOR_VERSION_PATCH 0)
set(SAIKO_INJECTOR_VERSION "${SAIKO_INJECTOR_VERSION_MAJOR}.${SAIKO_INJECTOR_VERSION_MINOR}.${SAIKO_INJECTOR_VERSION_PATCH}")

configure_file(
    ${CMAKE_CURRENT_SOURCE_DIR}/shared/version.h.in
    ${CMAKE_CURRENT_BINARY_DIR}/generated/version.h
    @ONLY
)
